<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="KYE-1000415093" name="cn.crazy.appium.testcases.ZhihuZhihuTest" tests="3" failures="1" timestamp="23 Aug 2018 08:25:27 GMT" time="53.507" errors="0">
  <testcase name="t002_search" time="12.930" classname="cn.crazy.appium.testcases.ZhihuZhihuTest"/>
  <testcase name="t003_guanzhu" time="16.059" classname="cn.crazy.appium.testcases.ZhihuZhihuTest">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.fail(Assert.java:101)
	at cn.crazy.appium.testng.Assertion.fail(Assertion.java:66)
	at cn.crazy.appium.testng.Assertion.assertEquals(Assertion.java:20)
	at cn.crazy.appium.testcases.ZhihuZhihuTest.t003_guanzhu(ZhihuZhihuTest.java:75)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:393)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- t003_guanzhu -->
  <testcase name="t001_login" time="24.518" classname="cn.crazy.appium.testcases.ZhihuZhihuTest"/>
</testsuite> <!-- cn.crazy.appium.testcases.ZhihuZhihuTest -->
